import { useState } from "react";
import { FileDown, Stethoscope, Loader2 } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { useLabReports } from "@/hooks/useLabReports";
import { toast } from "sonner";

const ConsultationSummary = () => {
  const { reports } = useLabReports();
  const [generating, setGenerating] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);

  const generateSummary = async () => {
    setGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-consultation-summary");
      if (error) throw error;
      setSummary(data?.summary || "No summary generated.");
    } catch (err: any) {
      console.error(err);
      toast.error("Failed to generate summary. Try again later.");
    } finally {
      setGenerating(false);
    }
  };

  const downloadPDF = () => {
    if (!summary) return;

    // Build a professional HTML document for printing as PDF
    const latestReport = reports[0];
    const html = `
<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>TIA - Thyroid Health Summary</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 40px 30px; color: #1a1a2e; line-height: 1.6; }
  .header { text-align: center; border-bottom: 3px solid #7c3aed; padding-bottom: 20px; margin-bottom: 30px; }
  .header h1 { color: #7c3aed; font-size: 24px; margin: 0 0 4px; }
  .header p { color: #666; font-size: 12px; margin: 0; }
  .section { margin-bottom: 24px; }
  .section h2 { color: #7c3aed; font-size: 16px; border-bottom: 1px solid #e5e5e5; padding-bottom: 6px; }
  .lab-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; margin: 12px 0; }
  .lab-item { background: #f8f7ff; padding: 12px; border-radius: 8px; text-align: center; }
  .lab-item .value { font-size: 20px; font-weight: bold; color: #7c3aed; }
  .lab-item .label { font-size: 11px; color: #666; text-transform: uppercase; }
  .lab-item .status { font-size: 11px; padding: 2px 8px; border-radius: 10px; display: inline-block; margin-top: 4px; }
  .status-normal { background: #dcfce7; color: #166534; }
  .status-elevated { background: #fef9c3; color: #854d0e; }
  .status-low { background: #ffedd5; color: #9a3412; }
  .summary-text { background: #f8f7ff; padding: 16px; border-radius: 8px; border-left: 4px solid #7c3aed; white-space: pre-wrap; font-size: 13px; }
  .footer { text-align: center; color: #999; font-size: 10px; margin-top: 40px; border-top: 1px solid #eee; padding-top: 16px; }
  .disclaimer { background: #fff7ed; border: 1px solid #fed7aa; padding: 12px; border-radius: 8px; font-size: 11px; color: #9a3412; margin-top: 20px; }
  @media print { body { padding: 20px; } }
</style></head><body>
<div class="header">
  <h1>🦋 TIA — Thyroid Health Summary</h1>
  <p>Generated on ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })} · Prepared for doctor consultation</p>
</div>

${latestReport ? (() => {
  const items = [
    { label: "TSH", value: latestReport.tsh, status: latestReport.tshStatus },
    { label: "T3", value: latestReport.t3, status: latestReport.t3Status },
    { label: "T4", value: latestReport.t4, status: latestReport.t4Status },
    { label: "Free T3", value: latestReport.ft3, status: latestReport.ft3Status },
    { label: "Free T4", value: latestReport.ft4, status: latestReport.ft4Status },
    { label: "Anti-TPO", value: latestReport.antiTPO, status: latestReport.antiTPOStatus },
  ].filter((m) => m.value !== null && m.value !== undefined);
  if (items.length === 0) return "";
  const statusClass = (s: string) => {
    const k = (s || "").toLowerCase();
    if (k === "normal") return "normal";
    if (k === "elevated" || k === "high") return "elevated";
    return "low";
  };
  return `
<div class="section">
  <h2>Latest Lab Values</h2>
  <div class="lab-grid">
    ${items.map((it) => `
    <div class="lab-item">
      <div class="label">${it.label}</div>
      <div class="value">${it.value ?? "N/A"}</div>
      <span class="status status-${statusClass(it.status)}">${it.status || "—"}</span>
    </div>`).join("")}
  </div>
  <p style="font-size: 11px; color: #666;">Total reports analyzed: ${reports.length}</p>
</div>`;
})() : ""}

<div class="section">
  <h2>AI Health Summary</h2>
  <div class="summary-text">${summary}</div>
</div>

<div class="disclaimer">
  ⚕️ <strong>Disclaimer:</strong> This summary is generated by TIA, an AI-powered thyroid companion. It is intended to support doctor-patient discussions and should NOT replace professional medical advice. Always consult your healthcare provider for diagnosis and treatment decisions.
</div>

<div class="footer">
  <p>Generated by TIA — Thyroid Intelligent Assistant<br/>
  This document is for informational purposes only.</p>
</div>
</body></html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
      win.onload = () => {
        win.print();
        URL.revokeObjectURL(url);
      };
    } else {
      // Fallback: download as HTML
      const a = document.createElement("a");
      a.href = url;
      a.download = `TIA_Health_Summary_${new Date().toISOString().slice(0, 10)}.html`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  return (
    <section className="relative z-10 px-6 pb-8">
      <div className="max-w-6xl mx-auto">
        <Card className="bg-white/5 backdrop-blur-md border-2 border-blue-400/40 hover:border-blue-400/70 transition-all duration-500 hover:shadow-[0_0_60px_hsl(220,80%,60%,0.3)] overflow-hidden">
          <CardContent className="p-8 md:p-10">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-full bg-gradient-to-br from-blue-500/20 to-purple-500/20">
                  <Stethoscope className="w-6 h-6 text-blue-300" />
                </div>
                <div>
                  <h2 className="text-xl md:text-2xl font-bold text-white">Doctor Consultation Summary</h2>
                  <p className="text-white/50 text-sm">Generate a professional summary for your doctor</p>
                </div>
              </div>
            </div>

            {!summary ? (
              <div className="text-center py-6">
                <p className="text-white/60 text-sm mb-4">
                  TIA will compile your lab trends, symptoms, and stability data into a clean, printable summary ready for your next appointment.
                </p>
                <Button
                  onClick={generateSummary}
                  disabled={generating || reports.length === 0}
                  className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white px-6"
                >
                  {generating ? (
                    <><Loader2 className="w-4 h-4 mr-2 animate-spin" />Generating...</>
                  ) : (
                    <><Stethoscope className="w-4 h-4 mr-2" />Generate Summary</>
                  )}
                </Button>
                {reports.length === 0 && (
                  <p className="text-white/40 text-xs mt-3">Upload lab reports first to generate a summary.</p>
                )}
              </div>
            ) : (
              <div className="space-y-4">
                <div className="bg-white/5 rounded-xl border border-blue-400/20 p-5">
                  <p className="text-white/80 text-sm leading-relaxed whitespace-pre-wrap">{summary}</p>
                </div>
                <div className="flex gap-3 justify-center">
                  <Button
                    onClick={downloadPDF}
                    className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white"
                  >
                    <FileDown className="w-4 h-4 mr-2" />Download / Print
                  </Button>
                  <Button
                    variant="ghost"
                    onClick={() => { setSummary(null); generateSummary(); }}
                    className="text-white/50 hover:text-white hover:bg-white/10"
                  >
                    Regenerate
                  </Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </section>
  );
};

export default ConsultationSummary;
